/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package FizzBuzzTree;

import org.junit.Test;
import sun.reflect.generics.tree.Tree;

import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testFizz() {
        TreeNode<String> treeNode = new TreeNode<>("3");
        App.fizzBuzzTree(treeNode);
        assertTrue("Should be Fizz", treeNode.getValue().equals("Fizz"));
    }

    @Test
    public void testBuzz() {
        TreeNode<String> treeNode = new TreeNode<>("5");
        App.fizzBuzzTree(treeNode);
        assertTrue("Should be Buzz", treeNode.getValue().equals("Buzz"));
    }

    @Test
    public void testFizzBuzz() {
        TreeNode<String> treeNode = new TreeNode<>("15");
        App.fizzBuzzTree(treeNode);
        assertTrue("Should be FizzBuzz", treeNode.getValue().equals("FizzBuzz"));
    }
}
