/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RepeatedWord;

import org.junit.Test;
import static org.junit.Assert.*;

public class RepeatedWordTest {
    @Test public void testSomeLibraryMethod() {
        RepeatedWord classUnderTest = new RepeatedWord();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
