/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RepeatedWord;

import org.junit.Test;
import static org.junit.Assert.*;

public class RepeatedWordTest {
    @Test public void testRepeatedWordOne() {
        String test = "Once upon a time, there was a brave princess who...";
        assertTrue("Should return the proper word",
                RepeatedWord.repeatedWord(test).equals("a")
        );
    }

    @Test public void testRepeatedWordTwo() {
        String test = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        assertTrue("Should return the proper word",
                RepeatedWord.repeatedWord(test).equals("it")
        );
    }

    @Test public void testRepeatedWordThree() {
        String test = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        assertTrue("Should return the proper word",
                RepeatedWord.repeatedWord(test).equals("summer")
        );
    }

    @Test public void testRepeatedWordFour() {
        String test = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi aliquip ex ea commodo consequat. Duis aute irure reprehenderit involuptate velit esse cillum eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";
        assertNull("Should return null",
                RepeatedWord.repeatedWord(test)
        );
    }
}
