/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

import java.util.ArrayList;
import java.util.HashSet;

public class TreeIntersection {
    public static ArrayList<Integer> treeIntersection(BinaryTree<Integer> treeA, BinaryTree<Integer> treeB) {
        HashSet<Integer> treeASet = new HashSet<>();
        HashSet<Integer> treeBSet = new HashSet<>();

        treeASet.addAll(treeA.preOrder());
        treeBSet.addAll(treeB.preOrder());
        treeBSet.retainAll(treeASet);
        return new ArrayList<Integer>(treeBSet);
    }
}
