/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DepthFirst;

import org.junit.Before;
import org.junit.Test;
import static java.util.Arrays.asList;
import static org.junit.Assert.*;

public class GraphTest {
    public Graph<String> graph;

    @Before
    public void setUp() {
        this.graph = new Graph<>();
        this.graph.addNode("A");
        this.graph.addNode("B");
        this.graph.addNode("C");
        this.graph.addNode("D");
        this.graph.addNode("E");
        this.graph.addNode("F");
        this.graph.addNode("G");
        this.graph.addNode("H");
        GraphNode<String> a = graph.getNodes().get(0);
        GraphNode<String> b = graph.getNodes().get(1);
        GraphNode<String> c = graph.getNodes().get(2);
        GraphNode<String> d = graph.getNodes().get(3);
        GraphNode<String> e = graph.getNodes().get(4);
        GraphNode<String> f = graph.getNodes().get(5);
        GraphNode<String> g = graph.getNodes().get(6);
        GraphNode<String> h = graph.getNodes().get(7);
        this.graph.addEdge(a, b, 1);
        this.graph.addEdge(a, d, 1);
        this.graph.addEdge(b, c, 1);
        this.graph.addEdge(c, g, 1);
        this.graph.addEdge(b, d, 1);
        this.graph.addEdge(d, e, 1);
        this.graph.addEdge(d, h, 1);
        this.graph.addEdge(d, f, 1);
        this.graph.addEdge(f, h, 1);
    }

    @Test public void testDepthFirstOne() {
        GraphNode<String> startNode = this.graph.getNodes().get(0);
        assertTrue("Should return the array in proper order",
                this.graph.depthFirst(startNode)
                        .equals(asList("A", "B", "C", "G", "D", "E", "H", "F"))
        );
    }

    @Test public void testDepthFirstTwo() {
        GraphNode<String> startNode = this.graph.getNodes().get(2);
        assertTrue("Should return the array in proper order",
                this.graph.depthFirst(startNode)
                        .equals(asList("C", "B", "A", "D", "E", "H", "F", "G"))
        );
    }

    @Test public void testDepthFirstThree() {
        GraphNode<String> startNode = this.graph.getNodes().get(6);
        assertTrue("Should return the array in proper order",
                this.graph.depthFirst(startNode)
                        .equals(asList("G", "C", "B", "A", "D", "E", "H", "F"))
        );
    }
}
