/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RepeatedWord;

import java.util.HashMap;

public class RepeatedWord {
    public static String repeatedWord(String longStringOfWords) {
        String words[] = longStringOfWords.split(" ");
        String tmpWord = "";
        HashMap<String, Integer> bagOfWords = new HashMap<>();

        for (String word: words) {
            // Regex taken from:
            // https://stackoverflow.com/questions/12506655/how-can-i-remove-all-leading-and-trailing-punctuation
            tmpWord = word.toLowerCase().replaceAll("[^a-zA-Z]+$", "");
            if (bagOfWords.containsKey(tmpWord))
                return tmpWord;
            else
                bagOfWords.put(tmpWord, 1);
        }
        return null;
    }
}
