/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class HashTableTest {
    public HashTable<Integer> testHT;

    @Before
    public void setUpHashTable() {

    }

    @Test public void testHTInstantiate() {
        HashTable<Integer> testHashTable = new HashTable<Integer>();
    }
}
