/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MultiBracketValidation;

import java.util.HashMap;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        if (args.length > 0)
            System.out.println(validateBrackets(args[0]));
        else
            System.out.println("Nothing to do!");
    }

    public static boolean validateBrackets(String input) {
        Stack<Character> stack = new Stack<>();

        HashMap<Character, Character> hMap = new HashMap<>();
        hMap.put('{', '}');
        hMap.put('[', ']');
        hMap.put('(', ')');

        for (Character c: input.toCharArray()) {
            if (c.equals('[') || c.equals('{') || c.equals('('))
                stack.push(c);
            if (c.equals(']') || c.equals('}') || c.equals(')'))
                if (stack.isEmpty() || !hMap.get(stack.pop()).equals(c))
                    return false;
        }

        return stack.isEmpty();
    }
}
