/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;

import static org.junit.Assert.*;

public class TreeIntersectionTest {
    public BinaryTree<Integer> bTreeA;
    public BinaryTree<Integer> bTreeB;

    @Before
    public void setUpBinaryTree() {
        TreeNode<Integer> rootA = new TreeNode<>(1);
        TreeNode<Integer> lA = new TreeNode<>(2);
        TreeNode<Integer> rA = new TreeNode<>(8);
        TreeNode<Integer> llA = new TreeNode<>(4);
        TreeNode<Integer> lrA = new TreeNode<>(5);
        TreeNode<Integer> rlA = new TreeNode<>(6);
        TreeNode<Integer> rrA = new TreeNode<>(7);
        rootA.setLeft(lA);
        lA.setLeft(llA);
        lA.setRight(lrA);
        rootA.setRight(rA);
        rA.setLeft(rlA);
        rA.setRight(rrA);
        this.bTreeA = new BinaryTree<Integer>();
        this.bTreeA.setRoot(rootA);

        TreeNode<Integer> rootB = new TreeNode<>(6);
        TreeNode<Integer> lB = new TreeNode<>(7);
        TreeNode<Integer> rB = new TreeNode<>(8);
        TreeNode<Integer> llB = new TreeNode<>(9);
        TreeNode<Integer> lrB = new TreeNode<>(10);
        TreeNode<Integer> rlB = new TreeNode<>(8);
        TreeNode<Integer> rrB = new TreeNode<>(12);
        rootB.setLeft(lB);
        lB.setLeft(llB);
        lB.setRight(lrB);
        rootB.setRight(rB);
        rB.setLeft(rlB);
        rB.setRight(rrB);
        this.bTreeB = new BinaryTree<Integer>();
        this.bTreeB.setRoot(rootB);
    }

    @Test public void testTreeIntersection() {
        assertTrue("Should be equal",
                TreeIntersection.treeIntersection(this.bTreeA, this.bTreeB)
                .equals(new ArrayList<>(Arrays.asList(6, 7, 8)))
        );
    }
}
