/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GetEdge;

import org.junit.Test;
import static org.junit.Assert.*;

public class GetEdgeTest {
    @Test public void testSomeLibraryMethod() {
    }
}
